### ISSUE TITLE
Questions about schema in a Rails application

### ISSUE THREAD

**Issue by andyhite** [zilverline/sequent#102]
First of all, let me just say that from my (so far) limited experience with this project, it's pretty great.

Here's my situation: we're interested in pursuing an event-sourced architecture for the application we're working on. It seems that we want to stick with Rails for a handful of reasons, instead of using a Sinatra app as the examples illustrate. So far, I have everything working – I'm able to execute commands, observe that the resulting events are being stored and my projections being created – but there are a few bits and pieces that I’m a little unsure about, mostly when it comes to schema management.

1) How should we be managing schema in a Rails environment? The documentation seems to be a little confusing when it comes to migrations in general – it says “it is strongly recommended to copy this schema into your first migration and then use migrations to keep it up to date”, then proceeds to say “view schema is not maintained through migrations” in the next section, and then the following section talks about “rake tasks for migrations”.

Does this mean that the Sequent schema should be loaded via a migration (e.g. `db/migrate/xxxxxxxxxxx_create_sequent_schema.rb`) as you would normally in a Rails app, but the view schema (for projections) should be loaded directly via something like `rake db:schema:load`? Or should *both* of these things be handled via a schema load task and traditional Rails migrations are out of the picture completely? If that’s the case, then the `migration_path` option for the “Rake Tasks for migrations” confuses me.

2) How should we set the schema search path in Rails? It’s generally done in the database.yml, but it seems like managing the view schema version in that would be difficult / redundant.

Honestly, if you can just give me a “For Dummies” explanation of how to handle schema for Sequent in Rails (which it seems you guys have done, judging by some replies in other issues) I would really be appreciative – as would others, I imagine.

Thanks!

**Comment by lvonk** [comment]
Hi @andyhite thanks for reaching out.

Indeed we are only managing the event store with migrations. Since that is pretty stable there are hardly any migrations for this other than the initial one. When the documentation talks about migrations it refers to the event store migrations. 

I now also realise I never created an example Rails app, although I mentioned that in a previous issue. My intent is to do this coming Friday.

But anyway the default approach for managing the view schema is to create it via `rake db:schema:load`. Most of our (non rails) projects have a setup like:

```ruby
module MyApp
  VIEW_PROJECTION = Sequent::Support::ViewProjection.new(
    name: "view",
    version: 1,
    definition: "db/view_schema.rb",
    event_handlers: [
      MyProjector.new
    ]
  )
end
```

The view_schema.rb
```ruby
Sequent::Support::ViewSchema.define(view_projection: App::VIEW_PROJECTION) do
  create_table :foos
end
```

In your `database.yml`, you can refer to the view schema as follows:

```ruby
database: &database
  host: localhost
  adapter: postgresql
  pool: 30
  encoding: utf8
  username: app_user
  schema_search_path: "event_store, <%= App::VIEW_PROJECTION.schema_name %>"
```

So let's say you add new tables and a projection you would update your `VIEW_PROJECTION`

```ruby
module MyApp
  VIEW_PROJECTION = Sequent::Support::ViewProjection.new(
    name: "view",
    version: 2,
    definition: "db/view_schema.rb",
    event_handlers: [
      MyProjector.new,
      AnotherProjector.new
    ]
  )
end
```
And add the necessary tables etc to `view_schema`.

Then you can use `rake view_schema:build` to create the new view schema in your deployment steps. This will rebuild the entire view schema.

Now this is the *default* approach. When your application grows and get millions of events (like one of our production apps), you probably need another strategy since replaying the entire view schema projections might take too long / too much space. This is something you need to consider before using. In one of our apps with over 20M events we are currently managing the view schema with normal sql files and replay completely in the background. We also do not replay the entire view schema but only the changed projectors. Since this is completely custom we haven't put it back in sequent yet. But maybe I will add some docs on how to do this, or if possible add it to sequent.

Please let me know if this helps or not. I will try to get an example sequent with Rails app on Friday.

**Comment by andyhite** [comment]
Thanks for the thorough response! That makes sense – I was actually able to figure out most of this with a little poking around, so it's nice to confirm everything with your reply.

I'm putting together a few "proofs of concept" using different event-sourcing libraries to decide which one we'll move forward with, and it seems down to Sequent or Eventide. I really like how you guys handle view schema, so regardless of the library we end up using I think I'll be applying some of these concepts.

**Comment by lvonk** [comment]
Cool that you managed to get most of it working. Good luck with your PoC!

**Comment by lvonk** [comment]
Hi @andyhite 

I have created a very basic example app using Rails, see the [examples project](https://github.com/zilverline/sequent-examples). 

Also see #103 for polished docs for the upcoming release.
