### ISSUE TITLE
Sharding EventStore ?

### ISSUE THREAD

**Issue by checkraiser** [zilverline/sequent#115]
Do you have any idea on sharding our EventStore ? ;)
Note: We have PgBouncer to keep consistent connection pooling, so sharding by just adding more databases is a good strategy.
But Sequent should have a built-in strategy to switch connection at runtime to find correct database to add to EventStore.
The `command_service` could have interface:
```
Sequent.command_service.switch(:shard).execute_commands(...)
```

**Comment by lvonk** [comment]
Hi,

Short answer: no

Longer answer: Internally the event store eventually uses the `pg` gem to access the database. The `Sequent::Core::EventRecord` is an `ActiveRecord` object. So if it can be done in Ruby with the `pg` gem and/or `ActiveRecord` it can be done in Sequent.

Also why do you need to shard? How many events do you have? 

Also why did you choose sharding over partitioning?

**Comment by checkraiser** [comment]
OK, let's do it one step at a time.
Will the `read models` raise error if error happenned on read side and rollback service transaction for a command ?

**Comment by lvonk** [comment]
Hi @checkraiser,

Everything that happens in `execute_commands` is by default in a single transaction. If an exception is raised then a rollback will occur.

What do you mean with `separate write and read in this case `?

**Comment by checkraiser** [comment]
@lonnv Currently, we have two places that can config `EventHandlers`:
1. In `Sequent.event_handlers`
2. In 
```
Sequent::Support::ViewProjection.new(
    name: "view",
    version: VERSION,
    definition: "db/view_schema.rb",
    event_handlers: [
      CounterRecordEventHandler.new
    ]
```
What's the difference ? 
And in a transaction , if there's an error in `EventHandler`, will Event be committed ?

**Comment by lvonk** [comment]
Hi,

Yes that is confusing in the current Sequent version and we are improving this in 3.0.  In fact `Sequent::Support::ViewProjection` will be deprecated in `3.0` (but still supported) and eventually be removed from Sequent.

So to take a step back: You have 2 types of EventHandlers: Projectors and Workflows. Projectors are used to **build up view state** in the database. Workflows are used to **take actions** based upon certain events (like sending email, or executing other commands).

In Sequent you configure all your EventHandlers (both Projectors and Workflows) in `Sequent.event_handlers`. These execute during normal operations of your application.

The EventHandlers defined in `Sequent::Support::ViewProjection` are the ones that are **only used during migration** of your view model. In this scenario it makes of course no sense to execute any workflows since that already "happened".

To come back at your question: By default if there is an error in an EventHandler the transaction will be rolled back and therefor the Event will **not** be committed.

btw @lonnv is my colleague, my handle is @lvonk :-)

**Comment by checkraiser** [comment]
@lvonk As i see, we can associate `aggregate_id` with a `database_url`, then we can shard our event_store architecture, we just need more `helpers` to do the blumping code here, like rake tasks to copy schema around multi database, code to add more `shards`, code to find correct database to attach current aggregate_id.
How do you think ?

**Comment by lvonk** [comment]
@checkraiser I am sorry, my sharding knowledge is limited, nor is it currently available in Sequent. So I am afraid I can't really help you here. Handling large event stores is on our wish list, but currently our focus is on getting sequent 3.0 out.

**Comment by checkraiser** [comment]
@lvonk I see, i think providing a wrapped HTTP API for Sequent is for 4.0 version ?

**Comment by lvonk** [comment]
Don't know if this will be part of Sequent, haven't thought of it actually.

**Comment by checkraiser** [comment]
@lonnv I think this is the way to go for new versions of Postgres:
- Partioning event stores via Foreign Data Wrappers.
What should be the partition key to you ?
