### ISSUE TITLE
About changing business rule

### ISSUE THREAD

**Issue by checkraiser** [zilverline/sequent#122]
I have one question about ES in general and Sequent specifically.
Old persisted events are recorded due to business rule.
So how about changing business rules could be handled ?
We have two things to do:
- Changing codes in command validation
- More processing when building view from old events data (so that invalid state couldn't be built)

How do you think about this problem ?

**Comment by lvonk** [comment]
1. Changes in command validation (and checks in your AggregateRoot) is not a problem. They only need to enforce the new business rules.
2. There is no "more processing" needed for building the view. Since in applying the events (containing the state) no business rules are enforced (in the `on` blocks) there is no invalid state.
