### ISSUE TITLE
Webhooks and events

### ISSUE THREAD

**Issue by sophiedeziel** [zilverline/sequent#167]
Here I am with other design questions. 

Let's say I use a web API and they send a lot of events with webhooks. For example, with Stripe, I would receive `invoice.created` once a month for each customer with monthly payments.

1. Should I receive the webhook and immediately send the data to the EventStore or should I create commands?

2. What would the `aggregate_id` be? Should I use the id Stripe provides or should I generate one that is unique to our system?

Thanks again for your time. The more I learn about Sequent and CQRS, the more I enjoy it.

**Comment by lvonk** [comment]
Hi,

1. We like to use commands for this, so the AggregateRoot can validate what happened. Although this is something your application should take for granted, since it comes from Stripe, you still want to check if for instance:
  a) you did not already recieve this invoice via the Stripe webhook
  b) maybe Stripe has bugs and the input is something unexpected
  c) Stripe changed the API and you were not aware of this. 
Also I think for the sake of consistency I like the fact that all "changes" are done via commands.

2. I would definitely go for generating your own `aggregate_id`. You do need to store the `stripe_id` as well, so you can check for uniqueness.

Hope this helps.

**Comment by sophiedeziel** [comment]
Yes it helps a lot! The validation part make a lot of sense and I like that everything should go through commands. 

Thank you for taking the time to answer questions.
