### ISSUE TITLE
Question - Why store Commands in the Event Store?

### ISSUE THREAD

**Issue by tomharvey** [zilverline/sequent#181]
I really enjoyed reading the other design questions in here and I'm trying to understand this all a lot better.

I'm left wondering why sequent stores the commands in the DB as well as the events? There is no clear way to interact with the commands, or did I miss something?

**Comment by lvonk** [comment]
Hi,

Storing commands is indeed not really needed for event sourcing. In Sequent we store commands, because they represent the users intent. This gives you the ability to implement a complete audit trail of all the changes (events) in your application.

You can interact with commands using the `Sequent::Core::CommandRecord` class.

**Comment by tomharvey** [comment]
got it - belt and braces? I thought it might be useful for auditing, good point about it being a more explicit log of the 'intent' fo the user than the resulting Events.

Thanks for the response!
