### ISSUE TITLE
Performance of uniqueness validation

### ISSUE THREAD

**Issue by reedlaw** [zilverline/sequent#225]
In the "Building a web application with Sequent" example there is a usernames aggregate responsible for validating uniqueness of Author emails. In practice, a system with thousands or millions of records could hardly perform well with such an implementation. In order to validate, all of the previous UsernameAdded event records must be instantiated as event objects in Ruby and iterated upon to create an array in `@usernames`. Then the `add` method does `fail UsernameAlreadyRegistered if @usernames.include?(username.downcase)`. How would this be handled in production? Can a projection be used to validate uniqueness?

**Comment by lvonk** [comment]
We use this implementation in production with ~ 40000 usernames in combination with [Snapshotting](https://www.sequent.io/docs/concepts/snapshotting.html), it performs fine.

In hindsight though I would not use event sourcing in this case since it potentially deals with 10.000s of events for a single aggregate and there is hardly any real business logic involved.
In this case I would just use a normal table with a unique index on the username column. You can not use a (sequent) projection for this, since those are rebuild using events.

One way to solve this is that you can mix event sourcing with non event sourcing in a single db transaction for instance. Or in other words use plan old active record migrations with Sequents `view_schema` and `event_store`. We use a separate db schema for all non event sourced tables, they are managed by plain old active record migrations. (See the [Rails & Sequent](https://www.sequent.io/docs/rails-sequent.html) guide on how to set this up). You can then use a synchronous workflow in which you insert a record in a table having a unique constraint on username. If that fails the entire transaction is rolled back and the user is not created.

Simplified example:
```ruby
class UserCommandHandler < Sequent::CommandHandler
  on CreateUser do |command|
    repository.add_aggregate(User.new(user.email, Sequent.new_uuid))
  end
end

class User < Sequent::AggregateRoot
  def initialize(email, id)
    super
    apply UserCreated, email: email
  end
end

class UsernamesWorkflow
    on UserCreated do |event|
       UserNames.create!(email: event.email, user_id: event.aggregate_id)
    end
end

# this can be a "normal" ActiveRecord table using a "normal" active record migration
class UserNames < ActiveRecord::Base
end
```
Hope this helps

**Comment by reedlaw** [comment]
@lvonk yes that does help tremendously. Thanks!

**Comment by Keoven** [comment]
Hello @lvonk, can you expound further on why a projection cannot be used? What are the pitfalls of adding a unique index on the projection?

**Comment by lvonk** [comment]
Uniqueness should be enforced by the domain, not a projection. A projection is derived from events. So whenever an event happened, the projection should accept it. A unique index can/will prevent that.
You can still add it as extra safety perhaps, but the domain should enforce uniqueness.

**Comment by Keoven** [comment]
@lvonk I see -- thanks for clarifying. This only means that on the domain, you'll have to also handle other cases like:

- Update the active record model in case there are update events.
- Properly seed/migrate data on your active record model in case the table already exists with actual records. (and resolve conflicts if any.)

**Comment by Keoven** [comment]
For the benefit of other people that might see this. Initially tried to enforce uniqueness on the projection for additional assurance. It works but if the chance of collision is high such as user inputted values, you'll most likely run into issues when you need to do a replay migration on the projections.
