### ISSUE TITLE
Are Separated Processors possible?

### ISSUE THREAD

**Issue by berkes** [zilverline/sequent#248]
Having built some services with a.o. [Event Sourcery](https://github.com/envato/event_sourcery), I'm used to the architecture where processors (Projectors, Reactors, Workflow etc) are handled in a separate thread or process. 

I don't see this mentioned with sequent; and from stepping through the code, I only encountered inline processing; i.e. the Command triggering the processing, instead of a reactive approach where some listener processes events on it's own.

Such distributed processing opens up a lot of opportunities. Obviously scaling out, but also having separate Bounded Contexts handle events in their own domain entirely. 

Is this possible already with Sequent? And if not, would it be something worth adding?

**Comment by lvonk** [comment]
Hi, out of the box Sequent does not have processors for handling events in a different process. Reason for this, up until now, that we do not want to make assumptions on which background processor people use and since it is quite easy to implement yourself using Workflows https://www.sequent.io/docs/concepts/workflow.html

The example on the page already shows how you can schedule something in the background using Delayed Job.

You can also choose to create a Workflows that wraps other Workflows for handling events in the background. For Delayed Job this would be:

```ruby
class DelayedWorkflow < Jortt::Workflow
  def initialize(workflows)
    @workflows = workflows
  end

  def handle_message(message)
    workflows = @workflows.select do |workflow|
      workflow.handles_message? message
    end

    workflows.each do |workflow|
        Delayed::Job.enqueue(
          DoAsynchronously.new(workflow, message),
        )
      end
    end
  end
end

class DoAsynchronously < Struct.new(:workflow, :event)
  def perform
    workflow.new.handle_message(event)
  end
end

# sequent config
Sequent.configuration.tap do |c|
  c.event_handlers = [
    DelayedWorkflow.new(
      [
        MyBackgroundWorkflow,
      ]
    )
  ]
end
```

Hope this answers you question.

**Comment by berkes** [comment]
>Hope this answers you question.

It does. Thanks.

While I think delayed jobs (via workflows) are one solution, they do solve the scaling issues, but don't solve the issue of "responsibilty".

With the current architecture, if I understand it correct, the main application is the one responsible for the code of-, logic around-, and the scheduling of- jobs. This is a pragmatic and clean approach, but it does require a monolith. It does not, from what I know, allow a separate Bounded Context to implement their own event-handler within their own domain and context that handles incoming events from another domain. E.g. both Marketing and RiskAnalysis might want to deal with an `BankAccountCreated` event in their very own way.

Such a reactive setup,  does require a lot of additional moving parts, though: projectors have to maintain trackers, locks and so on. As can be [seen in event_sourcery](https://github.com/envato/event_sourcery-postgres/blob/master/lib/event_sourcery/postgres/tracker.rb). All these moving parts add complexity.

**Comment by lvonk** [comment]
> With the current architecture, if I understand it correct, the main application is the one responsible for the code of-, logic around-, and the scheduling of- jobs. This is a pragmatic and clean approach, but it does require a monolith.

Indeed it does. We ❤️ majestic monoliths 😄 

>  It does not, from what I know, allow a separate Bounded Context to implement their own event-handler within their own domain and context that handles incoming events from another domain.

Well actually you can, but the Sequent way of doing this is that the Aggregate in the separate Bounded Context needs to create a new event based on the incoming event. Not sure if this is in conflict with the way Bounded Context is defined, or what is common practice, but in my opinion using the same event is just an implementation detail rather than it is prescribed somewhere.

**Comment by lvonk** [comment]
@berkes okay if I close this issue?

**Comment by berkes** [comment]
@lvonk sure!
