### ISSUE TITLE
Have to delete all snapshots on deployment

### ISSUE THREAD

**Issue by benchengggv** [zilverline/sequent#261]
https://www.sequent.io/docs/concepts/snapshotting.html
> Important: When you enable snapshotting you must delete all snapshots after each deploy. The AggregateRoot root state is dumped in the database. If in the new version the class definition of the AggregateRoots is changed the snapshotted state can not be loaded.

IIUC, the snapshot data is serialized using Marshal, meaning whenever the AggregateRoot Class have changed, we have to clear all Snapshot before deploy. Otherwise, it will failed to obtain correct object from Marshal.load.

references:
https://github.com/zilverline/sequent/blob/06916d8ba975919adb347c78bba2d24931bd9920/lib/sequent/core/aggregate_root.rb#L46
https://github.com/zilverline/sequent/blob/06916d8ba975919adb347c78bba2d24931bd9920/lib/sequent/core/aggregate_root.rb#L82

Consider when the system grow bigger and bigger, removing all Snapshot may mean replaying thousand(or more) of events upon loading a single Aggregate root, which is not flexible to a production system at all 🙈

So my questions are:
* Are there any workaround for this?
* If there are no smart workaround, do you think it's possible to use other approach to serialize the snapshot such that we don't have to remove snapshot upon AR class changed?

**Comment by lvonk** [comment]
Hi @benchengggv ,

You understand correctly. We indeed "suffer" from this problem ourselves, we  have around > 35.000 aggregates that need a snapshot, some > 1000s events. We generate these snapshots after each deploy, which is far from ideal, but also doesn't create that much problems actually. Not all of those aggregates are needed all of the time, so when it is loaded there is most probably already a snapshot for it.

One of the things we learned over that last years is don't create Aggregates with that many events, try to avoid this as much as possible. If not possible you need to enable snapshotting. There are currently no out-of-the-box workaround for this in Sequent. However Sequent does allow you to implement this yourself.

One approach would be to implement the serialization of the snapshot differently. For instance using json, or another mechanism you want to use. Currently you will need to subclass `AggregateRoot` with for instance your own `ApplicationAggregateRoot` and  override `load_from_history` and `take_snapshot!`.

Another solution to this problem is to do a, `AggregateRoot` rollover instead, we have been thinking about this ourselves, but the urge of necessity for us is not big enough yet. It goes something like this: Whenever an `AggregateRoot` has more events than a certain threshold, create a new `AggregateRoot` containing the entire state in a single event and keep pointers to each other for reference. 

For instance an over simplified implementation:

```ruby
class Usernames < AggregateRoot
  def initialize(id,  state, previous_aggregate_id)
    super(id)
    apply UsernamesCreated, state: state
    apply UsernamesPreviousIdSet, previous_aggregate_id: previous_aggregate_id
  end

  def rollover_if_needed
    if @sequence_number > SOME_THRESHOLD
      new_id = Sequent.new_uuid
      apply AggregateRolledOver, new_id: new_id
      # @state depends on what you want to track (e.g. the usernames)
      Usernames.new(new_id, @state, id)
    end
  end

  def some_method
    apply SomeEvent
    rollover_if_needed
  end
end
```

But keep in mind to either delegate calls to a rolled-over aggregate to the new one, or update all references to the rolled-over aggregate to the new one.

Again both approaches are not yet implemented, I think the first approach would be the "easiest" to implement.

**Comment by benchengggv** [comment]
Thanks @lvonk.
I have actually started a POC on using Json + Dry Struct to implement my own load_from_history and take_snapshot!

Maybe I can share here once I proved the POC works.

Approach 2 is very interesting but this sound like an overkill for me also🙂

**Comment by lvonk** [comment]
> Maybe I can share here once I proved the POC works.

Yes please do, this would also be nice to have in Sequent. For now I will close this ticket, but please update if you finished your POC.
