### ISSUE TITLE
Sequent on handling File Uploads (binaries)?

### ISSUE THREAD

**Issue by berkes** [zilverline/sequent#282]
I need to handle uploads and they must be handled through the event-store for replayability and auditability.

The Aggregate is a FileList that recieves AddFile commands (FileList.add_file()) emitting FileAdded events. Files with those events can be large (50MB or more). The FileList aggregate needs some info on the files: type, size. But not contents. 

The way I see it, I have several options for dealing with this. The entire file(the bytes) can be included in the event. Or the file can be stored elswere and a pointer to that file stored in the event (By Ref vers By Value).

Greg Young [says](https://groups.google.com/g/dddcqrs/c/6wkFP4wQKaA):
> Generally I put in a document/distributed file system and include a link to it on the event. 

In case of such a pointer (link, url), there are several places and options to store it and retrieve the pointer. Most notable candidates would be the CommandHandler, or the EventStore. 

When I look at sequent, the `EventStore.store_events` has no hooks or places where I could plug in something that "stores these event-attributes outside of the database". Having the EventStore handle this transparently would be nice, as the application can just add binaries to an event and stay ignorant about how this is handled.

My FileListCommandHandler could store the file and then call the `file_list.add_file(file_url, ...other_attrs)`,
but when I look at Commands, I see that these too are stored in EventStore.store_events, so the same storage issue applies. The Command can then not have the file contents, nor can it contain a pointer to a tmpfile as that would either make the stored commands either huge or obsolete - Yet I don't have or see a direct case to store the commands, though.

In both cases it is fine when storing the file (on a distributed storage like S3) is slow and blocking: storing the file, like storing the event, needs to be transactional anyway: we don't want events that point to files that could not be stored (but having files stored for events that could not be stored is less of a problem)

That leaves a third option, where the application layer (rack or sinatra, in this case) handles the storing: the business-domain just gets a link and knows nothing about actual files. For us that might work, but we would loose the ability to replay events or have tracable file-uploads event log. It is really just cheating, by leaving the file contents out of the domain. Which in many cases might be a valid decision, but not for us. And it opens a can-of-worms on reaping files that were later rejected by domain logic, for example.

Practical:
* How do any of you solve this with Sequent?
* Would it work to subclass Sequent::EventStore with my own Sequent::BinaryAwareEventStore which handles "binary attributes" or "file attributes" different from other attributes?
* Or would such an addition be welcome as PR to Sequent::EventStore?

For my BinaryAwareEventStore I'm thinking about a name convention driving this. E.g. a postfix of `_binary` to an attribute ensures it gets excluded from storage in the PG event store table. E.g. an InvoiceCreated#invoice_binary  attr would be stored to a file (in s3) and the url then stored in PG. And on-retrieval that invoice_binary gets filled with the contents of the file at the URL.
This may work for certain cases. But would be problematic with Huge Files as they are passed around in memory.
A prefix of `_pointer` would indicate this attribute contains a pointer to a *local file* e.g. InvoiceCreated#invoice_pointer would contain the path to the local file and on-storage uploads to e.g. s3. On retrieval it would fetch the file and store it locally and then fill that invoice_pointer with the path to this file. Memory-wise friendlier than the _binary version, but maybe a little more flakey.

I'm considering that this BinaryAwareEventStore would act upon all such attributes by convention, simply hardcoded that "if it is postfixed with _pointer it acts on that attribute. For me that would work, but I can think that for Sequent, as a PR, that would be too rigid and maybe lead to unexpected effects when someone has an attribute with such a name accidentally. 😬 Yet having configuration for this adds even more complexity.

**Comment by lvonk** [comment]
Hi @berkes 

> How do any of you solve this with Sequent?

We followed Greg Young's advice by storing them outside of the event store. We upload the files first to s3 and when that is successful put the reference in the command and event. I think this is the most practical and preferred solution since s3 is way better in storing files than a database is (and also cheaper :-)). 
Besides that you benefit from being able to serve them to the user in a web app directly using cloudfront for instance. So I guess we do the third option you describe. I this does not prevent us to replay events or anything btw, what do you mean with that? 
If a complete and traceable log you could design these steps in the domain of course.

- `RequestFileUploadUrl -> FileCreated,FileUploadUrlSet`
- User uploads via browser;
-- when successful `MarkFileAsUploaded -> FileUploaded`
-- when failed `MarkUploadFailed -> FileUploadFailed`

A workflow could then respond to `FileUploaded` doing your domain logic in validating the file. This way you keep a clear history of uploaded files that were rejected later? I feels like this is part of you domain as you describe it, rather then a can-of-worms.

> Would it work to subclass Sequent::EventStore with my own Sequent::BinaryAwareEventStore which handles "binary attributes" or "file attributes" different from other attributes?

If you would need to do something before storing an Event or Command I think the `SerializesEvent` and `SerializesCommand` modules are the places to look at and should be made pluggable. However in this case I would advice against it. Loading files in memory or storing them in a temp location on your server feels very brittle...

> Or would such an addition be welcome as PR to Sequent::EventStore?

A pluggable `SerializesEvent` and `SerializesCommand` that would make such a thing possible yes, but I am not sure about the `BinaryAwareEventStore`, but we are open to discuss more in detail.

**Comment by berkes** [comment]
Thanks for the reply. 

>  We upload the files first to s3 and when that is successful put the reference in the command and event. I think this is the most practical and preferred solution since s3 is way better in storing files than a database is (and also cheaper :-)).

This is the route I had in mind too. Indeed s3. 

 > So I guess we do the third option you describe.

For me, that would not really work, due to some constraints listed above: we really need them in the domain model.

* We need to be able to rebuild the state from events and these files are an important piece of t hat state. In fact, they are about the most important data :)
* we need tracability because an important business-case is that people have to provide the right files on time and then sign them (and only them) off.
* We need to send out messages (mail etc) on some uploads.
* We need to validate size.
* (in future) we must validate files on mime/type. To e.g. enforce images to only be images.

For now, I am trying the route of having my CommandHandler upload the file: 

```
class FilelistCommandHandler < Sequent::CommandHandler
  # ...
  on AddFile do |command|
    do_with_aggregate(command, Filelist) do |filelist|
      file_url = ''
      File.open(command.file_pointer, 'r') do |file|
        file_url = file_storage.store(file, command.aggregate_id)
      end
      filelist.add_file(url: file_url)
    end
  end

  def file_storage
    @file_storage ||= Adapters.config.event_file_storage
  end
end
```

The event_file_storage.store() is just an [adapter](https://en.wikipedia.org/wiki/Hexagonal_architecture_(software)) wrapping `Aws::S3:Client.put_object()` really.

From here, the Aggregate and Events only deal with the URL, and not the actual file contents.

One problem, is that up untill the CommandHandler i'm passing the file around. For now, I chose to pass around a pointer to the TempFile that rack [makes after receiving the file](https://github.com/rack/rack/blob/8be612ab949cf2eba7f4231ef17052a68315f911/lib/rack/multipart/uploaded_file.rb). 

Another problem is that the comment will be serialized and stored with a `file_pointer` that contains a filename and some metadata of a tmpfile: a file that in future makes no sense at all. But so far I am not using the stored commands yet.

> storing them in a temp location on your server feels very brittle

This is somewhat brittle indeed; but there is very little you can when relying on rack: it is the standard. We just need to ensure that this tmpfile stays around until we are done with the CommandHandle.  Which is fine, because rack keeps it around until the response is delivered and we will only deliver that response once the command is handled and events are stored.

So far, I am reasonably happy with this route. But my main question still is on the commands that are stored. So far, I don't even need any changes to sequent.

I could easily have the commandhandler change the command (e.g. replace the `command.file_pointer` with the url from s3) but It feelds wrong to modify the command right before it gets stored to the event-store. Does Sequent consider commands immutable? Or do you see it is a valid to have command-handlers append/update commands before they are commited?
I could also leave it as it is, with `file_pointer` pointing to nonexisting files once a command is loaded from the DB. since I'm not certain about the use-case of  the stored commands; but I'm afraid this might come haunt me later.

**Comment by lvonk** [comment]
I am still wondering if you can't model all those constraints as Events in your Aggregates instead of needing the actual file. Or course you need to parse and validate the file within the CommandHandler but are you also parsing / interpreting the file when replaying the Aggregate?

> but It feelds wrong to modify the command right before it gets stored to the event-store. Does Sequent consider commands immutable?

Sequent stores commands just to capture intent. Ideally you should not modify them after send, but in some cases, like passwords you need to encrypt them before storing. Like Sequent does with [Sequent::Secret](https://www.sequent.io/docs/concepts/types.html#sequentsecret). So it is really up to you if you want to do this or not.

_PS_ 
Some other thoughts I had reading through your case:
It feels to me like the parsing and interpreting of the files isn't your business logic, it feels to me that **the result of that parsing is**. Perhaps the parsing of the file should result in several command being executed.

As an example: In our application we parse and interpret bank files with transactions (also rather important for our domain). But we get them via several formats of files. Besides that we also receive them via several formats of API's.
After parsing and interpreting we create commands which are executed. The parsing is rather dumb and just translates the file to a command with all the attributes the domain needs to do its business logic (so in your case it would set mime/type, size, receive date, etc). This of course also contains the pointer to the file location, but the CommandHandler doesn't need it to do it's business logic. It only validates that there is a pointer.
The domain then can do logic like `apply FileRejected if type == 'foo' and size > 5.mb` or something similar. A `Workflow` can then respond to `FileRejected` and send out an email (if this is important to track this can also be another command resulting in events). 

_PS PS_ 
We eventually moved away from uploading via Rack because it also puts unnecessary load on our webservers. We upload directly to s3 via cloudfront and then parse and interpret all files in the background. This does result in extra modelling of events (the queueing and such) but results in a better user experience (and less load on our webservers).

**Comment by berkes** [comment]
Thanks for your time. This helps me a lot. I just hope I can do something back in the form of a PR or so :)

> Some other thoughts I had reading through your case:
> It feels to me like the parsing and interpreting of the files isn't your business logic, it feels to me that the result of that parsing is. Perhaps the parsing of the file should result in several command being executed.

I think part of the confusion stems from me being somewhat vague. My case is quite clear though:

We have a web-app that helps webdesigners and builders (and in future more niches) with their projects: e.g. let their customers pick dates for meetings, let customers sign off on deliveries and so on. All these are "steps" in a "project".

One such step is to "provide your texsts and images": a customer uploads their logo's, photo's, texts and once all is gathered, "signs them off". 
Another step is where the webdesigner up;pads deliveries (files) and the customer can accept or decline that. 

In all those cases it is of crucial importance that the exact files are known and can be reproduced at time of "Signing off".

I'm quite happy with the setup now, where my commandHandler manages the files and places it on S3. It then sends a hash, s3 url, and some other metadata to the FileList Aggregate, which captures those in events. The hash gives some guarantee that a file was not tampered with, the URL instead of the actual bytes, suffice as concept of "File". And the additional metadata (size, types etc) are used to validate and maintain state of that Aggregate.

I can imagine the setup where even the client sends directly to s3 to a signed s3 endpoint, would work for other cases like yours. E.g. a good setup for things like Avatars, or Product Images, I'd imagine.   
Again other cases, say where a user "uploads" a textfile that is then used to import things, the actual CSV, JSON, xml etc can be part of an ImportEvent - provided it is of reasonable size - I've done that in the past with GeoJSON: just store the entire json in the `GeoJSONFeatureCollectionImportedEvent`. 
Again another case, I think, is mine, here: where we need to be sure that the files which were present at Event X, are the actual files- but, indeed, we don't need the binary contents of those files in the events; just having pointers in form of URLS and hashes would be good.

**Comment by lvonk** [comment]
I see, then I think we are using almost the same setup with the exception of not we are passing in the binary data into a command but take care of the upload before.
And indeed in some cases, where the files (or messages from webhooks) contain json or something and are relatively small, we also store the entire content as json string in an event like you describe.

So many choices... :-)
