### ISSUE TITLE
New Installation : Unable to proceed beyond running migrations

### ISSUE THREAD

**Issue by mainangethe** [zilverline/sequent#416]
Trying to learn sequent.
Following instructions as per the tutorial on sequent.io site.

At the migrations steps, I'm running into an error.
![Screenshot 2024-08-14 at 19 21 00](https://github.com/user-attachments/assets/29a5376e-3d98-405d-a7a0-9f2dc55f5935)

### My Env
- Ruby: 3.2.1, I've also tried with 3.0.2 (Same issue)
- PG 16.3
- MacOS 12.7.4

**Comment by lvonk** [comment]
Hi @mainangethe , thanks for reporting. This issue if fixed in master but hasn't been released yet. Locate `sequent_schema.rb` in your project and replace with https://github.com/zilverline/sequent/blob/e748e9283111d5b708076fa62354a9ec691f3418/lib/sequent/generator/template_project/db/sequent_schema.rb. 
That should fix it. 
We are working on a new release, but it requires some more time since it involves some breaking changes.

**Comment by lvonk** [comment]
We released 7.1.0 so this should be fixed.
