### ISSUE TITLE
Rake tasks and rails integration

### ISSUE THREAD

**Issue by andriytyurnikov** [zilverline/sequent#91]
So far it looks like there is no obvious way to have drop-in installation into rails environment. 
Is it by design?
Also, what would you say, if I'll make a PR with all rake tasks prefixed with `sequent:` namespace ?

**Comment by lvonk** [comment]
> So far it looks like there is no obvious way to have drop-in installation into rails environment. 
Is it by design?

No not really. Sequent comes from non rails applications and we started to opensource it. We do however use it in Rails applications. But those apps will typically be an all Javascript front-end sending commands as json to some endpoint(s). And yes we are definitely lacking a good how-to / example app for setting this up in Rails, but it shouldn't be to hard... (hopefully).
Is this a new rails environment or an existing application you want to event source?


> Also, what would you say, if I'll make a PR with all rake tasks prefixed with `sequent:` namespace ?

Is this because it is conflicting with existing Rails tasks in a Rails app?

**Comment by andriytyurnikov** [comment]
@lvonk , well, obviously I am looking from rails corner now, still it may be a good idea as it is ;)

**Comment by lvonk** [comment]
Since we are actually using the active-record migrations I think it is better to leave it as `db:migrate` since that is what you would expect. 
Tomorrow I will look into an example in setting this up in Rails and polish the docs some more.
